language: python
python:
  - "3.6"
dist: xenial
cache: pip
script: pytest
install:
  - pip install -r requirements.txt
deploy:
  provider: pypi
  user: coolacid
  password:
    secure: sV4gtJeUf/yz/yQBj6LjYJ/sJRnGZai3fdr6blRay7cop4Ys220CO9f1pZOwF2TterzGktVvK5Qd69AEPwVvMvsP6IBLjYrg/ZpRN5U+74N02s4MRAZPGGF2/laagUo4Ry6Ms3WsciRaTdV+Ohduj2jRRY31UJDoHLej/bxPISfLVRpM16sWWn3P67cNT5H8jH7p1hiareZhEXkIdn8ufszmp+W6HK6WvgZDvuJaMf6ulChVoA97djZvfTzmmMts02ETFhFPBYAbLtug442WRiKH9Ikg3e1XfUW+BlxO200Ii1WajYouZSNf0elhgwuY/6qRE0nIb18AkBHxH6t6no5fJXo7jI9gY1Ef5t2ZPiKNf0D5oRQXYs7LmxvnCY6E8LuvucetWrzNG2/W6RQRFk7sOii2mMDrWp3Z6IgB9ZxVyGKHr0yWxAL1mD2UYXbzQokg3yDlAlqeScTQZFFFGhkLb/CigiWLe1006H03q3Tfo7Zp8fZnGiwZRCqBQJ3G4Et7UR4g96CPkmqgtF9yxolj7ufC5PCNBn5Pn39xbx9Fzfctzo5ScKIwA9WDxaWF+gRKB+pGV0KYkgQGF7jUmrwChS1xokFB1k6IauBiqjuTWq6RjeaM2VSpkVBcp0Ncq2XwkV9tMeZLrCP5pBtJKze8ay6ZEvd5pSiIRjcJoFM=
  on:
    tags: true
